markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Dancing With Nancy
production_url : http://adamclerk.github.com
description: "Fun with Nancy, Mono and .NET"
disqus_shortname: dancingwithnancy
analytics: UA-38822228-1
gauges: 
author :
  name : Adam Clark
  github : adamclerk
  twitter : adamclerk
